"""
_finalize_preflight.py  Pre-Flight Checks & Architect Fix
===========================================================
Extracted from mesh_finalize.py  handles background compilation,
syntax validation, and the Architect Syntax Fix invocation loop.

Exported:
    _run_preflight_checks(ctx) -> PipelineContext
"""

from __future__ import annotations

import re
import subprocess
import sys
from typing import Any, Dict, List, Optional

# ── SEARCH/REPLACE conflict-marker regex (inline — patch_regexes.py was deleted) ──
SEARCH_REPLACE_PATTERN = re.compile(
    r"<<<<<<<\s*SEARCH\n(.*?)\n=======\n(.*?)\n>>>>>>>\s*(?:REPLACE)?",
    re.DOTALL,
)

from models import PipelineContext
from _pipeline_helpers import atomic_write_text
from token_budget import TokenBudget
import _prompts as _prompts_mod  # live module ref  reads post-bootstrap values
from pipeline import (
    PROJECT_ROOT,
    call_ollama,
)


# ──────────────────────────────────────────────────────────────────────
#  Pre-Flight Checks: Compilation & Syntax Validation
# ──────────────────────────────────────────────────────────────────────

from _preflight_helpers import (
    _flush_results_to_workspace,
    _strip_search_replace_metadata,
    _is_comment_only,
    _task_has_code,
    _inject_empty_output_errors,
)  # noqa: F401

def _inject_static_pattern_errors(ctx: PipelineContext) -> None:
    """Delegated to _preflight_static  see that module for the full implementation."""
    from _preflight_static import _inject_static_pattern_errors as _ise
    _ise(ctx)

def _build_synthetic_scaffold(tid: str, domain: str, original_output: str) -> str:
    """Build a MINIMAL valid code scaffold when no clean anchor exists.

    Instead of re-using broken output that contains static guard violations
    (which poisoned every previous fix cycle), this function synthesises a
    minimal but syntactically valid scaffold so the fix model has valid
    structure to extend rather than garbage to repair.

    Returns a string of collapsed scaffold code suitable for use as an
    anchor block.
    """
    if domain == "Lua":
        # Extract any function name hints from the original output
        _scaffold_hints = ""
        _orig_funcs = re.findall(
            r'(?:local\s+)?function\s+(\w+)\s*\(',
            original_output or "",
        )
        if _orig_funcs:
            _scaffold_hints = (
                "\n-- Detected function(s) that need re-implementing:\n"
                + "\n".join(f"--   {f}(...)" for f in _orig_funcs[:5])
            )

        # Minimal valid Lua module scaffold  --  no static caches or globals.
        _scaffold = (
            f'-- Minimal scaffold for {tid}\n'
            f'-- Generated by synthetic-anchor builder (Failure Mode 4 fix)\n'
            f'-- Extend this scaffold with working code. Do NOT discard it.\n'
            f'\n'
            f'-- Engine lifecycle callbacks\n'
            f'function OnLoadStatic()\n'
            f'end\n'
            f'\n'
            f'function OnLoad()\n'
            f'end\n'
            f'\n'
            f'MidwayPhysics.OnStep(function(dt)\n'
            f'    -- TODO: implement per-frame logic\n'
            f'end)\n'
            f'\n'
            f'function OnUnload()\n'
            f'end\n'
            f'{_scaffold_hints}\n'
        )
    elif domain == "C++":
        _scaffold = (
            f'// Minimal scaffold for {tid}\n'
            f'// Generated by synthetic-anchor builder\n'
            f'#pragma once\n\n'
            f'#include <cstdint>\n\n'
            f'void {tid.replace("task_", "task").replace("-", "_")}_init() {{}}\n'
        )
    else:
        # Generic fallback: emit a minimal valid code block structure
        _scaffold = (
            f'// Minimal scaffold for {tid} ({domain})\n'
            f'// Generated by synthetic-anchor builder\n'
        )

    return TokenBudget._block_aware_collapse(_scaffold, 1500)


def _run_preflight_checks(ctx: PipelineContext) -> PipelineContext:
    """
    Phase 6 pre-flight: run background compilers (C++ / Make), Lua syntax
    checks, and Pro Mode unit test compilation/execution. If errors are
    detected, invoke the Architect Syntax Fix cycle to patch them.
    """
    print("  [Pre-Flight] Flushing results to workspace before compilation...")
    _flush_results_to_workspace(ctx)
    ctx.pre_flight_errors = ""

    # Universal guard: catch empty or prose-only outputs before any compiler runs.
    _inject_empty_output_errors(ctx)

    # Static pattern guard: catch known-bad patterns that are always wrong
    # regardless of compiler availability.
    _inject_static_pattern_errors(ctx)

    # Coverage check: every task in task_map must have a non-empty result.
    # Tasks that were never executed (e.g. the LLM dropped them) are surfaced
    # here so the fix loop has a concrete mandate to generate the missing output.
    # NOTE: In monolithic mode, ctx._monolithic_lua_target is set and the single
    # monolithic output satisfies ALL task coverage requirements. Skip per-task
    # checks to avoid flagging every task as "no output" when only the monolithic
    # result exists.
    if getattr(ctx, '_monolithic_lua_target', None):
        _mono_file = ctx._monolithic_lua_target
        print(f"  [Coverage Check] ⏭ Monolithic mode active (target: {_mono_file}) — "
              f"skipping per-task coverage check (monolithic output satisfies all tasks).")
    elif ctx.task_map:
        for _cov_tid, _cov_task in ctx.task_map.items():
            _cov_out = ctx.all_results_dict.get(_cov_tid, "")
            if not _cov_out or not _cov_out.strip():
                _cov_dom = getattr(_cov_task, "agent", "?")
                _cov_desc = getattr(_cov_task, "description", "") or getattr(_cov_task, "title", "")
                ctx.pre_flight_errors += (
                    f"\n## Missing Output  Task {_cov_tid} [{_cov_dom}]\n"
                    f"Task {_cov_tid} ({_cov_desc[:120]}) was planned but produced no output. "
                    f"A complete implementation is required for every planned task.\n"
                )
                print(f"  [Coverage Check] ⛔ Task {_cov_tid} [{_cov_dom}] has no output  injecting fix demand.")

    # Integration schema conflict check: handle ownership collisions across tasks.
    try:
        from integration_schema import validate_schema_conflicts
        _schema_conflict_text = validate_schema_conflicts(ctx)
        if _schema_conflict_text:
            ctx.pre_flight_errors += _schema_conflict_text
            print(f"  [IntegrationSchema] ⚡ Schema conflicts detected  injecting into preflight errors.")
    except Exception:
        pass

    # Feature coverage gap check: compare agent outputs against AttractionDesign checklist.
    _design = getattr(ctx, 'attraction_design', None)
    if _design and _design.feature_checklist:
        _all_output = "\n".join(ctx.all_results_dict.values())
        _gaps = []
        for _feature in _design.feature_checklist:
            # Heuristic: look for any 2+ consecutive non-stop-words from the
            # feature string appearing in the combined output.
            import re as _re_cov
            _keywords = [w for w in _re_cov.findall(r'\b\w{4,}\b', _feature.lower())
                         if w not in {'must', 'should', 'that', 'with', 'this', 'from', 'have', 'when', 'been', 'into', 'each'}]
            if _keywords and not any(kw in _all_output.lower() for kw in _keywords[:3]):
                _gaps.append(_feature)
        if _gaps:
            ctx.coverage_gaps = _gaps
            _gap_lines = "\n".join(f"  - {g}" for g in _gaps)
            ctx.pre_flight_errors += (
                f"\n## ⚠️  Feature Coverage Gaps (from Attraction Design checklist)\n"
                f"The following features from the design document appear to be missing from agent outputs:\n"
                f"{_gap_lines}\n"
                "Each agent responsible MUST ensure these features are implemented.\n"
            )
            print(f"  [Coverage Check] 📋 {len(_gaps)} design checklist item(s) appear missing.")
        else:
            print("  [Coverage Check] ✅ All design checklist items appear covered.")

    # Platform-aware compilation check
    _cmake_cache = ctx.project_root / "CMakeCache.txt"
    _makefile = ctx.project_root / "Makefile"
    try:
        if sys.platform == "win32":
            if not _cmake_cache.is_file():
                print("  [Pre-Flight] No CMakeCache.txt found  skipping cmake build check.")
            else:
                cmake_build = subprocess.run(
                    ["cmake", "--build", "."],
                    capture_output=True, text=True, cwd=ctx.project_root,
                    shell=True, timeout=30,
                )
                if cmake_build.returncode != 0:
                    err_tail = "\n".join(cmake_build.stderr.splitlines()[-50:])
                    # Discard cmake infrastructure errors  only propagate real compiler diagnostics.
                    _infra_error = any(
                        kw in err_tail.lower()
                        for kw in ("could not load cache", "no cmake_cache", "run cmake first",
                                   "cmake error", "cmake warning", "configuring incomplete")
                    )
                    if not _infra_error:
                        ctx.pre_flight_errors += f"\n## C++ Compiler Errors:\n```\n{err_tail}\n```"
                        # Circuit Breaker: isolate retry strikes to matching domain agents
                        failing_domains = ("C++", "PHYS", "NET", "SHADER")
                        for tid in list(ctx.all_results_dict.keys()):
                            task_obj = ctx.task_map.get(tid)
                            if task_obj and task_obj.agent in failing_domains:
                                ctx.retry_counts[tid] = ctx.retry_counts.get(tid, 0) + 1
                                print(f"  [Circuit Breaker] {tid} ({task_obj.agent}) retry_count incremented to {ctx.retry_counts[tid]} (build failure)")
                    else:
                        print(f"  [Pre-Flight] cmake infrastructure error suppressed (not a compiler diagnostic): {err_tail[:120]}")
        else:
            if not _makefile.is_file():
                print("  [Pre-Flight] No Makefile found  skipping make build check.")
            else:
                make_process = subprocess.run(
                    ["make", "-j4"], capture_output=True, text=True,
                    cwd=ctx.project_root, timeout=30,
                )
                if make_process.returncode != 0:
                    err_tail = "\n".join(make_process.stderr.splitlines()[-50:])
                    _infra_error = any(
                        kw in err_tail.lower()
                        for kw in ("no targets", "nothing to be done", "no rule to make")
                    )
                    if not _infra_error:
                        ctx.pre_flight_errors += f"\n## C++ Compiler Errors:\n```\n{err_tail}\n```"
                        # Circuit Breaker: isolate retry strikes to matching domain agents
                        failing_domains = ("C++", "PHYS", "NET", "SHADER")
                        for tid in list(ctx.all_results_dict.keys()):
                            task_obj = ctx.task_map.get(tid)
                            if task_obj and task_obj.agent in failing_domains:
                                ctx.retry_counts[tid] = ctx.retry_counts.get(tid, 0) + 1
                                print(f"  [Circuit Breaker] {tid} ({task_obj.agent}) retry_count incremented to {ctx.retry_counts[tid]} (build failure)")
                    else:
                        print(f"  [Pre-Flight] make infrastructure message suppressed: {err_tail[:120]}")
    except subprocess.TimeoutExpired:
        ctx.pre_flight_errors += "\n## Compiler Timeout:\n```\nC++ build timed out after 30s\n```\n"
    except Exception:
        pass

    # ── Pro Mode: Unit Test Compilation & Execution ────────────────────
    # Only runs when at least one task was actually flagged as math-heavy
    # and the user opted in (ctx.math_heavy_tasks is non-empty).
    if ctx.math_heavy_tasks:
        print("  [Pro Mode] Compiling and executing test suite...")
        test_build_dir = ctx.project_root / "build" / "tests"
        test_binary = test_build_dir / "run_tests"
        if sys.platform == "win32":
            test_binary = test_build_dir / "run_tests.exe"

        # Only attempt to build tests if a configured cmake build tree exists.
        _cmake_cache = ctx.project_root / "CMakeCache.txt"
        if not _cmake_cache.is_file():
            print("  [Pro Mode] No CMakeCache.txt  test binary build skipped (no configured build tree).")
            # Informational only  do NOT append to ctx.pre_flight_errors.
            # Writing here makes pre_flight_errors non-empty even after all real
            # violations are resolved, causing the arch-fix loop to fire on clean code.
        else:
            # Build test target if cmake project is configured
            test_build_ok = True
            try:
                test_build_proc = subprocess.run(
                    ["cmake", "--build", ".", "--target", "run_tests"],
                    capture_output=True, text=True, cwd=ctx.project_root,
                    shell=True, timeout=60,
                )
                if test_build_proc.returncode != 0:
                    test_build_ok = False
                    err_tail = "\n".join(test_build_proc.stderr.splitlines()[-50:])
                    _infra_kws = (
                        "could not load cache", "no cmake_cache", "run cmake first",
                        "cmake error", "cmake warning", "configuring incomplete",
                    )
                    if any(kw in err_tail.lower() for kw in _infra_kws):
                        print(f"  [Pro Mode] cmake infrastructure error suppressed during test build: {err_tail[:120]}")
                    else:
                        ctx.pre_flight_errors += (
                            f"\n## Test Suite Compilation Errors:\n```\n{err_tail}\n```\n"
                        )
                        print(f"  [Pro Mode] ⚠ Test suite failed to compile  treating as [VETO]")
            except (subprocess.TimeoutExpired, Exception) as e:
                test_build_ok = False
                ctx.pre_flight_errors += (
                    f"\n## Test Suite Compilation Exception:\n```\n{e}\n```\n"
                )

            if test_build_ok and test_binary.is_file():
                try:
                    test_run = subprocess.run(
                        [str(test_binary)], capture_output=True, text=True,
                        timeout=60,
                    )
                    if test_run.returncode != 0:
                        test_stderr = test_run.stderr.strip() or test_run.stdout.strip()
                        ctx.pre_flight_errors += (
                            f"\n## Unit Test Failures:\n```\n{test_stderr[:2000]}\n```\n"
                        )
                        print(f"  [Pro Mode] ⛔ Tests FAILED  feeding errors back to domain agents")
                    else:
                        print(f"  [Pro Mode] ✅ All unit tests passed!")
                except subprocess.TimeoutExpired:
                    ctx.pre_flight_errors += (
                        "\n## Unit Test Timeout:\n```\nTest binary timed out after 60s\n```\n"
                    )
                except Exception as e:
                    ctx.pre_flight_errors += (
                        f"\n## Unit Test Execution Error:\n```\n{e}\n```\n"
                    )

    # Scan both the real project tree and .staging_workspace/ so that files
    # flushed to staging (when staging mode is active) are also syntax-checked.
    from _helpers_io import is_staging_active, get_staging_path
    _lua_roots = [ctx.project_root]
    _staging_root = ctx.project_root / ".staging_workspace"
    if is_staging_active() and _staging_root.is_dir():
        _lua_roots.append(_staging_root)

    # Build a reverse map: relative-path string → task_id so that luac errors
    # can be attributed to the owning task and the fix model receives a labelled
    # mandate rather than a bare stderr dump.
    # Covers both regular tasks (target_file attr) and merged keys
    # (stored as "merged:<rel_path>" in all_results_dict).
    _lua_file_to_tid: dict = {}
    if ctx.task_map:
        for _rtid, _rtask in ctx.task_map.items():
            _tf = getattr(_rtask, "target_file", None) or getattr(_rtask, "output_file", None)
            if _tf:
                _lua_file_to_tid[str(_tf).replace("\\", "/")] = _rtid
    for _rkey in ctx.all_results_dict:
        if _rkey.startswith("merged:"):
            _rrel = _rkey[len("merged:"):]
            _lua_file_to_tid[_rrel.replace("\\", "/")] = _rkey
            # Also register under the bare filename so luac hits in the project
            # root (which only have lf.name, not the full relative path) still
            # resolve to a task ID instead of returning 'unknown'.
            _rbare = _rrel.replace("\\", "/").split("/")[-1]
            if _rbare not in _lua_file_to_tid:
                _lua_file_to_tid[_rbare] = _rkey

    _luac_missing = False
    # Track resolved absolute paths already checked so the merged file is never
    # reported more than once, even when both the project tree and the staging
    # tree contain a copy, or when multiple reverse-map keys point to the same
    # physical file.
    _luac_seen: set = set()
    for _lua_root in _lua_roots:
        if _luac_missing:
            break
        for lf in _lua_root.rglob("*.lua"):
            # Skip test harness files  they are not generated output and their
            # syntax errors must not inflate pre_flight_errors or trigger the
            # arch-fix loop.  Pattern covers test_task_N.lua and any file whose
            # stem starts with "test_task".
            if lf.stem.startswith("test_task"):
                continue

            # Deduplicate: resolve the canonical path and skip if already seen.
            try:
                _lf_canon = lf.resolve()
            except Exception:
                _lf_canon = lf
            if _lf_canon in _luac_seen:
                continue
            _luac_seen.add(_lf_canon)

            # Resolve the task-id for this file (used in error messages and
            # circuit-breaker).  Try both staging-relative and project-relative paths.
            _lf_rel = ""
            try:
                _lf_rel = lf.relative_to(_lua_root).as_posix()
            except ValueError:
                _lf_rel = lf.name
            _owning_tid = (
                _lua_file_to_tid.get(_lf_rel)
                or _lua_file_to_tid.get(lf.name)
            )

            try:
                lua_proc = subprocess.run(
                    ["luac", "-p", str(lf)],
                    capture_output=True, text=True, timeout=30,
                )
                if lua_proc.returncode != 0:
                    # luac writes errors to stderr; strip the temp-path prefix so
                    # the fix model sees a clean line/column reference.
                    _raw_err = lua_proc.stderr.strip()
                    # Replace the full absolute path with just the filename so the
                    # message is stable across machines and easier to read.
                    _clean_err = _raw_err.replace(str(lf), lf.name)

                    # Extract the first "line N" reference so we can surface it
                    # prominently in the mandate.
                    _line_ref = ""
                    _line_m = re.search(r':(\d+):', _clean_err)
                    if _line_m:
                        _line_ref = f" (line {_line_m.group(1)})"

                    _task_label = f"Task {_owning_tid}" if _owning_tid else f"file {lf.name}"
                    # Bug F guard: only feed syntax errors into preflight when the file
                    # is an owned task output.  Files with (owner: unknown) are pre-existing
                    # project files that were NOT generated by this pipeline run -- their
                    # syntax errors are not actionable by the fix loop and would trigger
                    # a spurious Architect Syntax Fix cycle on clean generated code.
                    if _owning_tid:
                        ctx.pre_flight_errors += (
                            f"\n## ⛔ Lua Syntax Error  {_task_label}\n"
                            f"**File:** `{lf.name}`{_line_ref}\n"
                            f"**luac output:**\n```\n{_clean_err}\n```\n"
                            f"**Fix mandate:** The Lua code for {_task_label} contains a syntax error "
                            f"and will NOT load in the engine. You MUST:\n"
                            f"1. Identify the exact line{_line_ref} reported above.\n"
                            f"2. Correct ONLY the syntax defect  do NOT rewrite unrelated code.\n"
                            f"3. Re-output the COMPLETE corrected Lua file prefixed with "
                            f"`### {_owning_tid or lf.stem}`.\n"
                            f"Do NOT emit prose, placeholders, or partial snippets.\n"
                        )
                        print(f"  [luac] ⛔ Syntax error in {lf.name}{_line_ref} "
                              f"(owner: {_owning_tid})")
                    else:
                        print(f"  [luac] ⚠ Skipping unowned file {lf.name}{_line_ref} "
                              f"(not a generated pipeline output  ignoring to prevent false-positive arch-fix)")

                    # Circuit-breaker: increment the owning task's retry counter so
                    # the review loop treats this file as actively failing and routes
                    # it to the fix agent on the next cycle.
                    if _owning_tid and _owning_tid in ctx.task_map:
                        ctx.retry_counts[_owning_tid] = (
                            ctx.retry_counts.get(_owning_tid, 0) + 1
                        )
                        print(f"  [Circuit Breaker] {_owning_tid} retry_count → "
                              f"{ctx.retry_counts[_owning_tid]} (luac syntax failure)")
                else:
                    print(f"  [luac] ✅ {lf.name}  syntax OK")
                    # Snapshot the luac-clean content so the fix loop can revert
                    # a later regression (mirrors the monolithic revert path).
                    _clean_map = getattr(ctx, '_last_luac_clean_anchor', None)
                    if _clean_map is not None and _owning_tid and _owning_tid in ctx.task_map:
                        _tf_rel = str(getattr(ctx.task_map[_owning_tid], 'target_file', '')).replace('\\', '/')
                        if _tf_rel:
                            try:
                                _clean_map[_tf_rel] = lf.read_text(encoding="utf-8", errors="replace")
                            except Exception:
                                pass

            except subprocess.TimeoutExpired:
                ctx.pre_flight_errors += (
                    f"\n## ⛔ Lua Syntax Error  {_task_label if '_task_label' in dir() else lf.name}\n"
                    f"**File:** `{lf.name}`\n"
                    f"```\nluac timed out after 30 s  file may be extremely large or contain an infinite loop at parse time.\n```\n"
                    f"**Fix mandate:** Investigate `{lf.name}` for runaway macro expansions or "
                    f"excessively deep table literals that cause the parser to hang.\n"
                )
            except FileNotFoundError:
                # luac is not installed  warn once and skip.
                # This should not happen after the DEVCOM.Lua winget install, but
                # the pipeline must remain functional in CI environments without it.
                print("  [Pre-Flight] ⚠ luac not found  Lua file-level syntax check skipped. "
                      "Install Lua 5.4 and ensure luac is on PATH for full syntax coverage.")
                _luac_missing = True
                break
            except Exception as _luac_ex:
                print(f"  [Pre-Flight] ⚠ luac check skipped for {lf.name}: {_luac_ex}")

    # ── Headless Runtime Simulation ─────────────────────────────────────────
    # Run the lightweight Lua tick harness against all Lua/physics task outputs.
    # Surfaces nil-handle access, bad API calls, and global pollution before
    # the output reaches the reviewer.  Non-fatal: errors become pre_flight_errors.
    try:
        from runtime_sim import run_runtime_sim
        _sim_errors = run_runtime_sim(ctx)
        if _sim_errors:
            ctx.pre_flight_errors += (
                "\n## ⚡ Runtime Simulation Errors\n"
                + "\n".join(f"  {e}" for e in _sim_errors)
                + "\n"
            )
            print(f"  [RuntimeSim] ⛔ {len(_sim_errors)} runtime error(s) detected.")
        else:
            print("  [RuntimeSim] ✅ No runtime simulation errors detected.")
    except Exception as _sim_ex:
        print(f"  [RuntimeSim] ⚠ Simulation skipped: {_sim_ex}")
    # Catches generated .py files with invalid syntax before the reviewer sees them.
    # Vendor / build directories are excluded to avoid false positives from
    # third-party code with deliberately non-standard syntax.
    _PY_SCAN_EXCLUDE = {
        "build", "vcpkg_installed", ".staging_workspace",
        "__pycache__", ".venv", "venv", ".git",
    }
    import ast as _ast
    for pf in ctx.project_root.rglob("*.py"):
        # Skip vendor/build trees and the pipeline's own top-level source.
        try:
            _pf_rel = pf.relative_to(ctx.project_root)
        except ValueError:
            continue
        # Exclude any file whose path contains a blacklisted directory component.
        if any(part in _PY_SCAN_EXCLUDE for part in _pf_rel.parts):
            continue
        # Only check files at least two levels deep so pipeline source itself
        # (e.g. _finalize_preflight.py at the root) is never re-checked.
        if len(_pf_rel.parts) < 2:
            continue
        try:
            _py_src = pf.read_text(encoding="utf-8", errors="replace")
            _ast.parse(_py_src, filename=str(pf))
        except SyntaxError as _se:
            ctx.pre_flight_errors += (
                f"\n## Python Syntax Error in {pf.name} (line {_se.lineno}):\n"
                f"```\n{_se.msg}: {_se.text}\n```\n"
            )
            print(f"  [Pre-Flight] ⛔ Python SyntaxError in {pf.name}:{_se.lineno}  {_se.msg}")
        except Exception:
            pass

    # ── F5: Per-Cycle luac Re-Validation ──────────────────────────────────────
    # After each fix cycle, re-run luac syntax checks on all affected .lua files
    # to detect regressions introduced by the fix model (Failure Mode 5).
    # Without this, a fix for task_2 can introduce syntax errors in the file that
    # was partially written by task_3, and the system never identifies which task
    # caused the regression.
    def _revalidate_lua_syntax(ctx, applied_tids: set) -> str:
        """Re-run luac syntax check on .lua files touched by the applied fixes.
        Returns a string of new syntax errors, or empty string if all pass.
        """
        _new_errors = ""
        if not applied_tids:
            return _new_errors
        # Collect target files from fixed tasks (abs path → relative key).
        _affected_files: dict = {}
        for _tid in applied_tids:
            _task_obj = ctx.task_map.get(_tid)
            if _task_obj and getattr(_task_obj, 'target_file', None):
                _tf = str(_task_obj.target_file).replace('\\', '/')
                _abs = ctx.project_root / _tf
                if _abs.is_file():
                    _affected_files[_abs] = _tf
        if not _affected_files:
            return _new_errors
        for _lf, _lf_rel in _affected_files.items():
            try:
                _lua_proc = subprocess.run(
                    ["luac", "-p", str(_lf)],
                    capture_output=True, text=True, timeout=30,
                )
                if _lua_proc.returncode != 0:
                    _raw_err = _lua_proc.stderr.strip().replace(str(_lf), _lf.name)
                    _tid_hint = ""
                    for _tid in applied_tids:
                        _task_obj = ctx.task_map.get(_tid)
                        if _task_obj and str(getattr(_task_obj, 'target_file', '')).replace('\\', '/') == _lf_rel:
                            _tid_hint = f" (regression from fix for {_tid})"
                            break
                    # Revert-on-regression: restore the last luac-clean snapshot
                    # (or the clean scaffold baseline) so a bad fix cycle can never
                    # persist a syntax-broken file.  Mirrors the monolithic path.
                    _clean_map = getattr(ctx, '_last_luac_clean_anchor', None) or {}
                    _clean_snap = _clean_map.get(_lf_rel)
                    if _clean_snap:
                        try:
                            atomic_write_text(_lf, _clean_snap)
                            print(f"  [Post-Fix luac] ⛔ Syntax error  REVERTED {_lf.name} "
                                  f"to last luac-clean snapshot ({len(_clean_snap)} chars).")
                            continue
                        except Exception as _rv_e:
                            print(f"  [Post-Fix luac] \u26a0 revert failed for {_lf.name}: {_rv_e}")
                    _new_errors += (
                        f"\n## ⛔ Post-Fix Lua Syntax Error  {_lf.name}{_tid_hint}\n"
                        f"**File:** `{_lf.name}`\n"
                        f"**luac output:**\n```\n{_raw_err}\n```\n"
                        f"**Fix mandate:** A previous fix cycle has introduced a syntax error.\n"
                        f"Re-fix the syntax defect immediately.\n"
                    )
                    print(f"  [Post-Fix luac] ⛔ Syntax error in {_lf.name} after fix cycle{_tid_hint}")
                else:
                    print(f"  [Post-Fix luac] ✅ {_lf.name}  syntax OK after fix cycle")
                    # Refresh the clean snapshot when the fix kept the file valid.
                    _clean_map = getattr(ctx, '_last_luac_clean_anchor', None)
                    if _clean_map is not None:
                        try:
                            _clean_map[_lf_rel] = _lf.read_text(encoding="utf-8", errors="replace")
                        except Exception:
                            pass
            except subprocess.TimeoutExpired:
                _new_errors += f"\n## ⛔ Post-Fix Lua Syntax Error  {_lf.name}\nluac timed out after 30s\n"
            except FileNotFoundError:
                print("  [Post-Fix luac] ⚠ luac not found  skipping post-fix validation.")
                break
            except Exception as _le:
                print(f"  [Post-Fix luac] ⚠ Error re-checking {_lf.name}: {_le}")
        return _new_errors

    # ── Architect Syntax Fix Cycle ─────────────────────────────────────
    # Bug G guard: only trigger arch-fix for ACTUAL syntax violations
    # (Lua Syntax Error, Static Pattern, Empty Output, Python Syntax).
    # Do NOT trigger for RuntimeSim phantom-API or economy/modifier
    # warnings, which are feature-completeness checks that the arch-fix
    # model cannot meaningfully repair and would only confuse it into
    # rewriting the entire file (producing a worse implementation).
    _RUNTIMESIM_MARKERS = [
        "Runtime Simulation Errors",
        "[PhantomAPIGate]",
        "Missing modifier consumption",
        "Missing economy hook",
        "Phantom colon-method",
        "Unknown MidwayPhysics API",
        "Unknown economy API",
        "Unknown Engine API",
    ]
    _has_syntax_errors = any(
        m in ctx.pre_flight_errors
        for m in ("## ⛔ Lua Syntax Error", "## Static Pattern", "## Missing Output",
                  "## Python Syntax Error", "## C++ Compiler Errors",
                  "## Test Suite", "## Unit Test")
    )
    if ctx.pre_flight_errors and not _has_syntax_errors:
        # Only RuntimeSim or non-actionable errors remain  --  skip the syntax
        # arch-fix cycle, but KEEP them in pre_flight_errors so they (1) surface
        # to the reviewer via the PASS-override gate and (2) block approval at
        # the consensus gate.  The PhantomAPIGate (Phase 6c) is a SEPARATE
        # deterministic phantom-API check and does NOT cover runtime errors.
        print("  [Pre-Flight] ⚠ Non-syntax preflight errors detected (RuntimeSim/PhantomAPI) "
              "-- skipping arch-fix cycle. Runtime errors will surface to the reviewer "
              "and block approval until resolved.")
    elif ctx.pre_flight_errors:
        print("  [Pre-Flight] Syntax errors detected. Forcing Architect Syntax Fix (per-domain).")

        # E16: Snapshot outputs that are both non-empty AND free of static guard
        # violations as the anchor for the arch fix.  Anchoring to a broken output
        # (the previous behaviour) re-introduces the same errors on every cycle.
        # Strategy: re-run the guard patterns against each output; only outputs
        # with zero matches are eligible as anchors.
        _GUARD_PATTERNS_QUICK = [
            re.compile(r'MidwayPhysics\.SpawnStaticPlane', re.IGNORECASE),
            re.compile(r'MidwayPhysics\.ApplyForce\b', re.IGNORECASE),
            re.compile(r'MidwayPhysics\.SpawnStaticMesh\s*\(\s*[\'"]', re.IGNORECASE),
            re.compile(r'^(?!\s*--).*(?<!MidwayPhysics\.)\bDestroyBody\s*\(', re.IGNORECASE | re.MULTILINE),
            re.compile(r'\bsol\s*\.\s*(?:set_function|new_usertype|state)\s*\(', re.IGNORECASE),
            # Phantom APIs that the Lua system prompt previously taught the model to use.
            # If any of these appear in an output it must never become a clean anchor.
            re.compile(r'\bsol\s*\.\s*log(?:_message)?\s*\(', re.IGNORECASE),
            re.compile(r'\bMidwayPhysics\s*\.\s*log(?:_message)?\s*\(', re.IGNORECASE),
            re.compile(r'\bMidwayPhysics\s*\.\s*FindBodyByLabel\s*\(', re.IGNORECASE),
            re.compile(r'\bMidwayPhysics\s*\.\s*SetPosition\s*\(', re.IGNORECASE),
            # Undefined booth globals  never defined in the Midway runtime.
            re.compile(r'\b(?:BUTTON|SLOT_[XYZ]|SharedBooth)\b', re.MULTILINE),
        ]
        _last_good: dict = {}
        for _tid, _out in ctx.all_results_dict.items():
            if not _out or not _out.strip() or _is_comment_only(_out):
                continue
            if not _task_has_code(_out):
                continue
            # Reject if any quick guard fires on this output
            if any(p.search(_out) for p in _GUARD_PATTERNS_QUICK):
                continue
            _last_good[_tid] = _out

        # Guard: skip any block the LLM filled with an [ERROR] stub, a bare
        # delegation token, or a placeholder  these would poison the next cycle.
        _error_stub_re = re.compile(
            r'^\s*(\[ERROR\]|\[DELEGATE|\[QUERY:DOC|\[CONF:|\[REVISE|<<<<<<|import sys'
            r'|name .sys. is not defined'
            r'|int task_\d+_solution|void task_\d+_solution)',
            re.IGNORECASE | re.MULTILINE
        )

        # Group failing tasks by domain so each call is scoped to one language.
        # This prevents qwen2.5-coder from being asked to write Lua, C++, and
        # PHYS simultaneously and falling back to language-agnostic placeholders.
        # NOTE: Task uses .agent (canonical domain key like "Lua", "C++") not .domain.
        #
        # Only include tasks that actually have violations in pre_flight_errors.
        # Previously ALL tasks were fed into the fix call regardless of whether
        # they were broken, causing 12-task batches that blew the context budget.
        _failing_tids_set: set = set(re.findall(r'\btask_\d+\b', ctx.pre_flight_errors))

        from collections import defaultdict
        domain_task_groups: dict = defaultdict(list)
        for tid, output in ctx.all_results_dict.items():
            if _failing_tids_set and tid not in _failing_tids_set:
                continue  # no violations for this task  skip it
            task_obj = ctx.task_map.get(tid)
            domain = (task_obj.agent if task_obj and getattr(task_obj, 'agent', None)
                      else "Unknown")
            domain_task_groups[domain].append((tid, output))

        # Split large task lists into small batches so each fix call stays well
        # under the pre-summarizer threshold (~24000 chars for 7B/8B models).
        # 3 tasks × 3000-char anchor + errors + cheatsheet ≈ 13000 chars  safe.
        _FIX_BATCH_SIZE = 3

        def _iter_domain_batches(groups, batch_size):
            for _d, _pairs in groups.items():
                for _i in range(0, max(1, len(_pairs)), batch_size):
                    yield _d, _pairs[_i:_i + batch_size]

        for domain, task_pairs in _iter_domain_batches(domain_task_groups, _FIX_BATCH_SIZE):
            # Build labelled task blocks  LLM is explicitly instructed to
            # echo back the same ### task_N header so the extraction regex works.
            task_blocks = [f"### {tid}\n{output}" for tid, output in task_pairs]
            domain_code_str = "\n\n".join(task_blocks)
            failing_tids = [tid for tid, _ in task_pairs]

            # E16: Build per-task anchor blocks from the last-good snapshot.
            # Collapsed to a safe budget via block-aware paging so VRAM is not
            # blown by injecting multiple large outputs simultaneously.
            # 2026-05-21: Increased from 1500 → 3000 because the original
            # budget collapsed to 65-75% truncation for 2-task Lua scenarios,
            # causing the fix model to discard real code and regenerate stubs.
            _ANCHOR_BUDGET = 3000  # chars per task anchor (was 1500)
            _anchor_blocks = []
            for _atid, _aout in task_pairs:
                _anchor = _last_good.get(_atid)
                if _anchor:
                    _collapsed_anchor = TokenBudget._block_aware_collapse(_anchor, _ANCHOR_BUDGET)
                    _anchor_blocks.append(
                        f"### {_atid} [ANCHOR  repair this, do NOT rewrite from scratch]\n"
                        f"{_collapsed_anchor}"
                    )
                elif _aout and _aout.strip():
                    # No clean anchor — build a MINIMAL synthetic scaffold
                    # instead of re-using broken output as the anchor.
                    # The dirty output contains violations that poisoned every
                    # previous fix cycle (Failure Mode 4). A synthetic scaffold
                    # gives the fix model valid structure to build on.
                    _synthetic_scaffold = _build_synthetic_scaffold(_atid, domain, _aout)
                    _anchor_blocks.append(
                        f"### {_atid} [MINIMAL SYNTHETIC SCAFFOLD — extend this, do NOT discard]\n"
                        f"{_synthetic_scaffold}"
                    )
            _anchor_str = (
                "\n\n## Previous Implementation (ANCHOR)\n"
                "The following is the last known implementation for each task.\n"
                "You MUST base your fix on this code. Do NOT discard it and write an empty scaffold.\n"
                + "\n\n".join(_anchor_blocks)
                + "\n"
            ) if _anchor_blocks else ""

            # Build a compact bridge cheatsheet for the fix model so it has
            # approved names in front of it  not just error messages.
            # Consolidated: delegate to the shared builder in _finalize_review
            # instead of maintaining a second inline copy here.
            _fix_cheatsheet = ""
            try:
                from pipeline import _CTX as _pf_ctx
                if _pf_ctx is not None:
                    from _finalize_review import build_fix_bridge_snippet as _bfbs
                    _base_snippet = _bfbs(_pf_ctx)
                    if _base_snippet:
                        _fix_cheatsheet = (
                            "\n## \u26a1 Approved Bridge API (exhaustive \u2014 use ONLY these names)\n"
                            + _base_snippet
                            + "Substitution quick-ref:\n"
                            + "  SetPosition/Teleport \u2192 MoveKinematic(h,lx,ly,lz,dt)\n"
                            + "  ApplyForce \u2192 ApplyImpulse(handle,ix,iy,iz)\n"
                            + "  CheckCollision \u2192 IsSensorTriggered(handle) \u2192 bool\n"
                            + "  table.clear(t) \u2192 for k in pairs(t) do t[k]=nil end\n"
                        )
            except Exception:
                pass

            # E17: Extract the exact required signature from the error block so the
            # fix model sees the CORRECT call pattern directly  not buried inside
            # a 3000-char collapsed error blob.  Without this, the model guesses
            # (e.g. adding a boolean flag) instead of copying the known-correct form.
            _signature_extract = ""
            _sig_marker = "**Required call signature:** "
            for _line in ctx.pre_flight_errors.splitlines():
                if _sig_marker in _line:
                    _signature_extract += _line.strip() + "\n"
            if _signature_extract:
                _signature_extract = (
                    "\n## ⚡ CORRECT SIGNATURE (from pre-flight checker  copy this EXACTLY)\n"
                    + _signature_extract
                    + "Use the EXACT positional signature shown above. "
                    "Do NOT add extra arguments, boolean flags, table literals, or labels.\n"
                )

            fix_input = (
                f"Domain: [{domain}]\n"
                f"The following {domain} task(s) failed pre-flight checks.\n"
                f"Errors:\n{TokenBudget._block_aware_collapse(ctx.pre_flight_errors, 3000)}\n"
                f"{_fix_cheatsheet}"
                f"{_signature_extract}"
                f"{_anchor_str}"
                f"CRITICAL OUTPUT FORMAT RULES (violations will be discarded):\n"
                f"1. Output ONLY working {domain} code. Do NOT output any [DELEGATE:...],"
                f" [QUERY:DOC:...], [CONF:...], prose explanations, or placeholder stubs.\n"
                f"2. Prefix EACH task's fixed code block with its exact header line: ### task_N\n"
                f"   Example for two tasks:\n"
                f"   ### task_1\n   ```lua\n   -- corrected code here\n   ```\n\n"
                f"   ### task_2\n   ```lua\n   -- corrected code here\n   ```\n"
                f"3. Do NOT invent new API names. Use ONLY the exact names from the Approved Bridge API list above.\n"
            )

            # Build a compact, repair-specific system prompt for the fix call.
            # Deliberately does NOT use get_agent_system(domain): that function
            # injects the full Lua runtime prompt + mesh protocol + virtual-memory
            # protocol (~11.8 k chars), leaving only ~469 chars for user content
            # and causing the model to produce scaffolds instead of real repairs.
            # The fix model already receives the approved API cheatsheet and anchor
            # code in the user message, so a short repair mandate is sufficient.
            _base_fix_system = _prompts_mod.ARCHITECT_FIX_SYSTEM
            # Append the domain-specific prohibitions from the cartridge so the
            # fix model still knows phantom APIs and lifecycle rules, but skip
            # the full ledger, mesh, and virtual-memory protocols.
            _domain_prohibitions = ""
            try:
                from pipeline import _CTX as _pf_ctx2
                if _pf_ctx2:
                    _cart = getattr(_pf_ctx2, 'mounted_cartridge', None)
                    if _cart:
                        _cart_domain = _cart.domains.get(domain)
                        if _cart_domain:
                            _sp = _cart_domain.system_prompt or ""
                            # Extract only up to 1800 chars from the domain prompt
                            # (enough for lifecycle + bridge rules)  no mesh/ledger.
                            _domain_prohibitions = "\n\n## Domain Rules (summary)\n" + _sp[:1800]
                    if not _domain_prohibitions:
                        _ctx_reg = getattr(_pf_ctx2, 'domain_registry', None) or {}
                        _dreg = _ctx_reg.get(domain, {})
                        if isinstance(_dreg, dict) and _dreg.get('system_prompt'):
                            _domain_prohibitions = "\n\n## Domain Rules (summary)\n" + _dreg['system_prompt'][:1800]
            except Exception:
                pass
            domain_system = _base_fix_system + _domain_prohibitions

            # Use domain-specific model: prefer live cartridge registry, then kernel dict
            _live_registry = getattr(ctx, 'domain_registry', None) or {}
            from pipeline import ALL_DOMAINS as _kernel_domains
            fix_model = (
                _live_registry.get(domain, {}).get('model')
                or _kernel_domains.get(domain, {}).get('model')
                or __import__('pipeline').EXECUTION_MODEL
            )

            fixed_str = call_ollama(
                domain_system, fix_input,
                f"Architect Syntax Fix [{domain}]", fix_model
            )

            # Strip the <fix-plan> reasoning block so it never contaminates
            # SEARCH/REPLACE extraction or gets stored as generated code.
            fixed_str = re.sub(r"<fix-plan>.*?</fix-plan>", "", fixed_str, flags=re.DOTALL).strip()

            # ── Primary extraction: LLM used required ### task_N headers ────
            # The regex tolerates any trailing label the model echoes after the
            # task ID (e.g. "### task_1 [ANCHOR  repair this...]") because the
            # prompt injects such labels and the model verbatim-echoes them.
            # Previously the regex required ONLY whitespace after the ID, causing
            # every arch-fix round to produce "no valid block" and retain bad code.
            applied_tids: set = set()
            for match in re.finditer(
                r"###\s*(task_\d+)[^\n]*\n(.*?)(?=###\s*task_\d+|\Z)", fixed_str, re.DOTALL
            ):
                tid = match.group(1).strip()
                fixed_code = match.group(2).strip()
                if not fixed_code or _error_stub_re.search(fixed_code):
                    print(f"  [Arch Fix] Skipping stub/error block for {tid} ({domain}) "
                          f" LLM did not produce valid code.")
                    continue
                if _is_comment_only(fixed_code) or not _task_has_code(fixed_code):
                    print(f"  [Arch Fix] Skipping comment-only/empty block for {tid} ({domain}) "
                          f" output contains no real implementation.")
                    continue
                if tid in applied_tids:
                    print(f"  [Arch Fix] ⚠ Duplicate block for {tid} ({domain})  ignoring second copy.")
                    continue
                if tid in ctx.all_results_dict:
                    _af_code = _strip_search_replace_metadata(fixed_code)
                    # Guard: refuse to introduce duplicate function definitions.
                    # When multiple tasks all target the same file and the LLM
                    # fix generates e.g. "function OnLoadStatic() end" for each
                    # one, this guard prevents the file from accumulating
                    # duplicates. Check if this fix would create a duplicate
                    # in the aggregated file.
                    _af_task_obj = ctx.task_map.get(tid)
                    if _af_task_obj and getattr(_af_task_obj, 'target_file', None):
                        _af_target_file = str(_af_task_obj.target_file).replace('\\', '/')
                        # Build the aggregated merged output for this file
                        _af_merged_lines = {}
                        for _af_mtid, _af_mout in ctx.all_results_dict.items():
                            if _af_mtid.startswith('merged:') and _af_target_file in _af_mtid:
                                _af_merged_lines[_af_mtid] = _af_mout
                            elif _af_mtid != tid:
                                _af_mtobj = ctx.task_map.get(_af_mtid)
                                if _af_mtobj and getattr(_af_mtobj, 'target_file', None):
                                    if str(_af_mtobj.target_file).replace('\\', '/') == _af_target_file:
                                        _af_merged_lines[_af_mtid] = _af_mout
                        # Check for duplicate function definitions in the fix
                        _af_new_funcs = set(re.findall(r'^function\s+(\w+)\s*\(', _af_code, re.MULTILINE))
                        _af_existing_funcs = set()
                        for _af_v in _af_merged_lines.values():
                            if _af_v:
                                _af_existing_funcs.update(
                                    re.findall(r'^function\s+(\w+)\s*\(', _af_v, re.MULTILINE)
                                )
                        _af_dupes = _af_new_funcs & _af_existing_funcs
                        if _af_new_funcs and _af_dupes:
                            # Strip the duplicate function definitions from the fix
                            # by removing "function <name>...end" blocks that already exist
                            for _af_dfunc in _af_dupes:
                                _af_old_count = len(_af_code)
                                # Remove the duplicate function definition
                                _af_code = re.sub(
                                    r'function\s+' + re.escape(_af_dfunc) + r'\s*\([^)]*\)[^e]*?end\s*',
                                    '',
                                    _af_code,
                                    count=1
                                )
                                if len(_af_code) < _af_old_count:
                                    print(f"  [Arch Fix] \u26a0 Stripped duplicate function '{_af_dfunc}' "
                                          f"from fix for {tid} (already defined by another task)")
                    # Guard: refuse to replace a real implementation with a stub.
                    # If the incoming fix is >40% shorter than the current code
                    # AND fewer than 5 non-blank lines, treat it as a regression stub.
                    _existing = ctx.all_results_dict[tid]
                    _existing_lines = [l for l in _existing.splitlines() if l.strip()]
                    _af_lines = [l for l in _af_code.splitlines() if l.strip()]
                    _shrink_ratio = (len(_existing) - len(_af_code)) / max(len(_existing), 1)
                    if _shrink_ratio > 0.40 and len(_af_lines) < 5:
                        print(f"  [Arch Fix] \u26a0 Refusing stub regression for {tid} ({domain}) "
                              f"({len(_af_lines)} lines vs {len(_existing_lines)} existing, "
                              f"{_shrink_ratio:.0%} smaller).")
                        continue
                    # Guard: refuse full-file lifecycle rewrites (the boilerplate
                    # signature).  Anchor tasks fill ONE -- [TASK_N_INSERT_HOOK]
                    # region; a fix that redefines the core lifecycle hooks is the
                    # model rewriting the whole file as a scaffold, which replaces
                    # real code with stubs and then triggers revert-to-skeleton.
                    _lifecycle_redefs = set(re.findall(
                        r'^function\s+(OnLoadStatic|OnLoad|OnUnload)\s*\(', _af_code, re.MULTILINE
                    ))
                    if _lifecycle_redefs:
                        print(f"  [Arch Fix] Refusing full-file lifecycle rewrite for {tid} "
                              f"({domain}) - redefines {sorted(_lifecycle_redefs)} "
                              f"(anchor tasks must patch their hook, not rebuild the file).")
                        continue
                    ctx.all_results_dict[tid] = _af_code
                    # Keep all_results list in sync.
                    _af_found = False
                    for _af_i, _af_e in enumerate(ctx.all_results):
                        if _af_e.get("task_id") == tid:
                            ctx.all_results[_af_i] = {"task_id": tid, "output": _af_code}
                            _af_found = True
                            break
                    if not _af_found:
                        ctx.all_results.append({"task_id": tid, "output": _af_code})
                    applied_tids.add(tid)
                    print(f"  [Arch Fix] ✅ Applied fix for {tid} ({domain})")
                    # Invalidate stale merged key so next flush uses patched output.
                    _af_task_obj = ctx.task_map.get(tid)
                    if _af_task_obj and getattr(_af_task_obj, 'target_file', None):
                        _af_rel = str(_af_task_obj.target_file).replace('\\', '/')
                        _af_mk = f'merged:{_af_rel}'
                        if _af_mk in ctx.all_results_dict:
                            del ctx.all_results_dict[_af_mk]
                            getattr(ctx, 'merged_file_registry', {}).pop(_af_rel, None)
                            print(f'  [Arch Fix] Invalidated stale merged key for {_af_rel}')
                    # Ledger: record final committed signatures (arch-fix may be
                    # the first time real code appears for a task that delegated)
                    try:
                        from ledger import update_internal_api_ledger
                        update_internal_api_ledger(_af_code, domain)
                    except Exception:
                        pass


            # ── SEARCH/REPLACE conflict-marker extraction ──
            # Check for Git-style <<<<<<< SEARCH / ======= / >>>>>>> REPLACE blocks
            # before falling back to standard markdown code fences.
            # Compute unapplied HERE so the SR loop below can reference it.
            # (It is also recomputed after the SR block in case more tids were
            # applied; the final fallback path computes it one more time too.)
            unapplied = [t for t in failing_tids if t not in applied_tids]
            sr_blocks = list(SEARCH_REPLACE_PATTERN.finditer(fixed_str))
            if sr_blocks:
                # Map SR blocks to unapplied tasks by target_file matching.
                # When a SEARCH/REPLACE block matches a target file, broadcast
                # the fix to ALL unapplied tasks targeting that same file.
                for sr_match in sr_blocks:
                    search_text = sr_match.group(1).strip()
                    replace_text = sr_match.group(2).strip()
                    if not search_text or not replace_text:
                        continue
                    # Pack as a dict-like tuple for _strip_search_replace_metadata
                    sr_payload = f"<<<<<<< SEARCH\n{search_text}\n=======\n{replace_text}\n>>>>>>> REPLACE"
                    matched_file = None
                    # Try to find a task whose file contains search_text
                    for tid in unapplied:
                        task = ctx.task_map.get(tid)
                        if task and task.target_file:
                            target_path = ctx.project_root / task.target_file
                            if target_path.is_file():
                                file_content = target_path.read_text(encoding="utf-8", errors="replace")
                                if search_text in file_content:
                                    matched_file = task.target_file
                                    break
                    if matched_file:
                        # Broadcast the patch to ALL unapplied tasks targeting this file
                        for tid in list(unapplied):
                            task = ctx.task_map.get(tid)
                            if task and task.target_file == matched_file:
                                _sr_code = _strip_search_replace_metadata(sr_payload)
                                ctx.all_results_dict[tid] = _sr_code
                                _sr_f = False
                                for _sr_i, _sr_e in enumerate(ctx.all_results):
                                    if _sr_e.get("task_id") == tid:
                                        ctx.all_results[_sr_i] = {"task_id": tid, "output": _sr_code}
                                        _sr_f = True
                                        break
                                if not _sr_f:
                                    ctx.all_results.append({"task_id": tid, "output": _sr_code})
                                applied_tids.add(tid)
                                print(f"  [Arch Fix] ✅ SEARCH/REPLACE matched for {tid} ({task.target_file})")
                    # No file match  try all unapplied tasks if only one SR block
                    if len(sr_blocks) == 1 and len(unapplied) > 0:
                        # Single SR block: apply to first unapplied task
                        tid = unapplied[0]
                        if tid in ctx.all_results_dict:
                            _srnm_code = _strip_search_replace_metadata(sr_payload)
                            ctx.all_results_dict[tid] = _srnm_code
                            _srnm_f = False
                            for _srnm_i, _srnm_e in enumerate(ctx.all_results):
                                if _srnm_e.get("task_id") == tid:
                                    ctx.all_results[_srnm_i] = {"task_id": tid, "output": _srnm_code}
                                    _srnm_f = True
                                    break
                            if not _srnm_f:
                                ctx.all_results.append({"task_id": tid, "output": _srnm_code})
                            applied_tids.add(tid)
                            print(f"  [Arch Fix] ✅ SEARCH/REPLACE applied (no file match) for {tid}")
                # Recompute unapplied after SEARCH/REPLACE extraction
                unapplied = [t for t in failing_tids if t not in applied_tids]
                if not unapplied:
                    continue

            # ── Fallback extraction: LLM ignored headers but produced code ──
            # When only one task is failing OR the LLM produced exactly one
            # fenced code block, apply it to all un-patched failing tasks.
            unapplied = [t for t in failing_tids if t not in applied_tids]
            if unapplied:
                _fence_re = re.compile(r"```[^\n]*\n(.*?)```", re.DOTALL)
                code_blocks = [
                    m.group(1).strip() for m in _fence_re.finditer(fixed_str)
                    if m.group(1).strip()
                    and not _error_stub_re.search(m.group(1))
                    and not _is_comment_only(m.group(1))
                    and _task_has_code(m.group(1))
                ]
                if len(code_blocks) == 1 and len(unapplied) == 1:
                    # Single block, single un-patched task  safe 1:1 apply.
                    tid = unapplied[0]
                    if tid in ctx.all_results_dict:
                        _sb_code = _strip_search_replace_metadata(code_blocks[0])
                        ctx.all_results_dict[tid] = _sb_code
                        _sb_found = False
                        for _sb_i, _sb_e in enumerate(ctx.all_results):
                            if _sb_e.get("task_id") == tid:
                                ctx.all_results[_sb_i] = {"task_id": tid, "output": _sb_code}
                                _sb_found = True
                                break
                        if not _sb_found:
                            ctx.all_results.append({"task_id": tid, "output": _sb_code})
                        print(f"  [Arch Fix] ✅ Applied single-block fallback fix for {tid} ({domain})")
                        try:
                            from ledger import update_internal_api_ledger
                            update_internal_api_ledger(code_blocks[0], domain)
                        except Exception:
                            pass
                elif len(code_blocks) == 1 and len(unapplied) > 1:
                    # One block returned for multiple un-patched tasks.
                    # NEVER broadcast a single skeleton to all tasks  doing so
                    # silently collapses a full multi-section implementation into
                    # the last task's narrow fix snippet.  Instead, reject the
                    # response and inject a hard error demanding one ### task_N
                    # block per task so the fix model must re-emit all sections.
                    from collections import defaultdict
                    file_tasks: dict = defaultdict(list)
                    for tid in unapplied:
                        task = ctx.task_map.get(tid)
                        tf = task.target_file if task else None
                        file_tasks[tf or "__no_file__"].append(tid)
                    resolved_any = False
                    for target_file, tids in file_tasks.items():
                        if target_file == "__no_file__" or len(tids) <= 1:
                            continue
                        # Multiple tasks share this file  refuse the single block.
                        print(
                            f"  [Arch Fix] \u26a0 Refused to broadcast single block to "
                            f"{len(tids)} task(s) for {target_file} ({domain})  "
                            "would collapse implementation. Demanding per-task blocks."
                        )
                        ctx.pre_flight_errors += (
                            f"\n## Arch Fix Output Rejected  {domain} ({target_file})\n"
                            f"The fix agent returned exactly 1 code block for {len(tids)} "
                            f"tasks ({', '.join(tids)}) that all write to `{target_file}`.\n"
                            f"Broadcasting a single block would overwrite all tasks with "
                            f"only one task's implementation, discarding the rest.\n"
                            f"**Required:** Output one `### task_N` block per task, each "
                            f"containing the COMPLETE implementation for that task. "
                            f"Tasks: {', '.join(tids)}.\n"
                        )
                    # Single-task file groups are still safe to apply 1:1
                    for target_file, tids in file_tasks.items():
                        if target_file == "__no_file__" or len(tids) != 1:
                            continue
                        tid = tids[0]
                        if tid not in ctx.all_results_dict:
                            continue
                        patched_content = _strip_search_replace_metadata(code_blocks[0])
                        ctx.all_results_dict[tid] = patched_content
                        applied_tids.add(tid)
                        _bc_found = False
                        for _bc_i, _bc_e in enumerate(ctx.all_results):
                            if _bc_e.get("task_id") == tid:
                                ctx.all_results[_bc_i] = {"task_id": tid, "output": patched_content}
                                _bc_found = True
                                break
                        if not _bc_found:
                            ctx.all_results.append({"task_id": tid, "output": patched_content})
                        resolved_any = True
                        print(f"  [Arch Fix] \u2705 Applied fix for {tid} ({domain})")
                    # Legacy broadcast path removed  see comment above.
                    if False:
                        first_tid = ""
                        if first_tid in ctx.all_results_dict:
                            applied_tids.add(first_tid)
                            # Mark ALL remaining tasks for this file as applied.
                            for tid in tids:
                                if tid != first_tid:
                                    applied_tids.add(tid)
                                    if tid in ctx.all_results_dict:
                                        ctx.all_results_dict[tid] = patched_content
                                        _bc_f2 = False
                                        for _bc_i2, _bc_e2 in enumerate(ctx.all_results):
                                            if _bc_e2.get("task_id") == tid:
                                                ctx.all_results[_bc_i2] = {"task_id": tid, "output": patched_content}
                                                _bc_f2 = True
                                                break
                                        if not _bc_f2:
                                            ctx.all_results.append({"task_id": tid, "output": patched_content})
                            resolved_any = True
                            print(f"  [Arch Fix] ✅ Broadcast single block to {len(tids)} task(s)"
                                  f" for {target_file} ({domain})")
                            try:
                                from ledger import update_internal_api_ledger
                                update_internal_api_ledger(code_block, domain)
                            except Exception:
                                pass
                            break
                    if not resolved_any:
                        print(f"  [Arch Fix] ⚠ Single block cannot be broadcast  "
                              f"no matching file found for {len(unapplied)} tasks ({domain})")
                elif len(code_blocks) == len(unapplied):
                    # One block per un-patched task  zip in order
                    for tid, blk in zip(unapplied, code_blocks):
                        if tid in ctx.all_results_dict:
                            _oz_code = _strip_search_replace_metadata(blk)
                            ctx.all_results_dict[tid] = _oz_code
                            _oz_found = False
                            for _oz_i, _oz_e in enumerate(ctx.all_results):
                                if _oz_e.get("task_id") == tid:
                                    ctx.all_results[_oz_i] = {"task_id": tid, "output": _oz_code}
                                    _oz_found = True
                                    break
                            if not _oz_found:
                                ctx.all_results.append({"task_id": tid, "output": _oz_code})
                            print(f"  [Arch Fix] ✅ Applied ordered fallback fix for {tid} ({domain})")
                            try:
                                from ledger import update_internal_api_ledger
                                update_internal_api_ledger(_oz_code, domain)
                            except Exception:
                                pass
                else:
                    # The batch arch-fix model returned nothing usable for these
                    # tasks.  Rather than retaining known-broken output and cycling
                    # into the next review/fix loop with the same errors, re-execute
                    # each failing task individually through its original scripter
                    # agent  the same path that produced the first output  but
                    # with the preflight errors injected as targeted feedback into
                    # task.context so the model knows exactly what to fix.
                    #
                    # Guard rails:
                    #   - Circuit breaker: if retry_counts[tid] >= 3 we stop
                    #     re-executing (same threshold as the wave validator) to
                    #     prevent an infinite spin on a task the model genuinely
                    #     cannot solve.  The broken output is retained as-is and
                    #     the review cycle will surface it as a hard failure.
                    #   - execute_task is imported lazily to avoid circular imports
                    #     (preflight → _helpers_exec → pipeline → preflight).
                    #   - task.context is temporarily extended with a focused error
                    #     summary then restored, so the retry is self-contained and
                    #     doesn't pollute later iteration context.
                    #   - If execute_task itself raises, the broken output is kept
                    #     and a warning is printed  we never crash the pipeline.
                    try:
                        from _helpers_exec import execute_task as _exec_task
                    except ImportError:
                        _exec_task = None

                    for tid in unapplied:
                        _strike = ctx.retry_counts.get(tid, 0)
                        if _strike >= 3:
                            print(f"  [Arch Fix] ⛔ Circuit breaker: {tid} ({domain}) "
                                  f"has {_strike} strike(s)  skipping re-execution, "
                                  f"retaining broken output.")
                            continue

                        if _exec_task is None:
                            print(f"  [Arch Fix] ⚠ execute_task unavailable for {tid} "
                                  f"({domain})  retaining previous output.")
                            continue

                        task_obj = ctx.task_map.get(tid)
                        if not task_obj:
                            print(f"  [Arch Fix] ⚠ No task object for {tid} "
                                  f"({domain})  retaining previous output.")
                            continue

                        # Build a compact, focused error summary for this task only.
                        # Pull only the violation blocks that mention this tid so
                        # the model isn't distracted by sibling errors.
                        _per_task_errors = "\n".join(
                            line for line in (ctx.pre_flight_errors or "").splitlines()
                            if tid in line or "## Static Pattern" in line
                               or "## Arg Count" in line or "## Phantom" in line
                               or "## Duplicate" in line or "## Scope" in line
                        )
                        if not _per_task_errors.strip():
                            _per_task_errors = TokenBudget._block_aware_collapse(
                                ctx.pre_flight_errors, 600
                            )

                        _error_injection = (
                            f"\n\n## ⚠ Pre-Flight Failures  You MUST fix ALL of these\n"
                            f"{_per_task_errors}\n"
                            f"Re-implement the task correctly. "
                            f"Do NOT repeat any of the violations listed above."
                        )

                        # Temporarily extend task.context with the error feedback.
                        _saved_context = task_obj.context or ""
                        task_obj.context = _saved_context + _error_injection

                        ctx.retry_counts[tid] = _strike + 1
                        print(f"  [Arch Fix] 🔁 Re-executing {tid} ({domain}) via "
                              f"original scripter (strike {ctx.retry_counts[tid]}/3)...")

                        try:
                            _new_output = _exec_task(
                                task_obj,
                                user_prompt=ctx.user_prompt,
                                director_output=ctx.director_output,
                                all_results=ctx.all_results_dict,
                                file_context="",
                                gdd_context=ctx.gdd_context,
                            )
                            # If Ollama is down, execute_task returns a fatal
                            # error sentinel.  Stop retrying this task  the
                            # circuit breaker will already be armed, and we
                            # must not overwrite existing output with an error
                            # string that looks like code to downstream phases.
                            try:
                                from ollama_client import is_fatal_ollama_error as _is_fatal
                            except ImportError:
                                _is_fatal = None
                            if _is_fatal and _is_fatal(_new_output):
                                print(f"  [Arch Fix] ⛔ Ollama error during re-execution of "
                                      f"{tid} ({domain})  aborting retries for this task.")
                                ctx.retry_counts[tid] = 3  # arm circuit breaker
                            elif (_new_output and _new_output.strip()
                                    and not _is_comment_only(_new_output)
                                    and _task_has_code(_new_output)):
                                _re_code = _strip_search_replace_metadata(_new_output)
                                # Reject re-executed Lua output that still contains
                                # bare namespace violations (CreatePool / PoolAcquire /
                                # PoolFree / PoolReturn without MidwayPhysics. prefix).
                                # These pass _task_has_code() but will fail the next
                                # static guard cycle, wasting another round.
                                _bare_ns_re = re.compile(
                                    r'(?<!MidwayPhysics\.)'  # not already prefixed
                                    r'\b(CreatePool|PoolAcquire|PoolFree|PoolReturn|MoveKinematic)\s*\(',
                                    re.MULTILINE,
                                )
                                if domain == "Lua" and _bare_ns_re.search(_re_code):
                                    print(f"  [Arch Fix] ⚠ Re-execution output for {tid} "
                                          f"({domain}) still contains bare namespace calls "
                                          f" rejecting and retaining previous output.")
                                else:
                                    ctx.all_results_dict[tid] = _re_code
                                    # Sync all_results list.
                                    _re_found = False
                                    for _re_i, _re_e in enumerate(ctx.all_results):
                                        if _re_e.get("task_id") == tid:
                                            ctx.all_results[_re_i] = {"task_id": tid, "output": _re_code}
                                            _re_found = True
                                            break
                                    if not _re_found:
                                        ctx.all_results.append({"task_id": tid, "output": _re_code})
                                    print(f"  [Arch Fix] ✅ Re-execution produced valid output "
                                          f"for {tid} ({domain}).")
                                    try:
                                        from ledger import update_internal_api_ledger
                                        update_internal_api_ledger(_re_code, domain)
                                    except Exception:
                                        pass
                            else:
                                print(f"  [Arch Fix] ⚠ Re-execution output for {tid} "
                                      f"({domain}) is empty/comment-only  retaining "
                                      f"previous output.")
                        except Exception as _re_err:
                            print(f"  [Arch Fix] ⚠ Re-execution raised for {tid} "
                                  f"({domain}): {_re_err}  retaining previous output.")
                        finally:
                            # Always restore context so later iterations are clean.
                            task_obj.context = _saved_context

    # ── Post-Fix Re-Validation ─────────────────────────────────────────────
    # After the arch-fix cycle patches task outputs, re-run the static checks
    # so ctx.pre_flight_errors reflects only violations that are STILL present.
    # Without this, the review loop's PASS-override at line ~535 of
    # _finalize_review.py would block approval on errors that were already fixed.
    if ctx.pre_flight_errors:
        print("  [Pre-Flight] Re-validating after arch-fix to clear resolved errors...")
        ctx.pre_flight_errors = ""
        # Re-flush so patched task outputs (and invalidated merged keys) land on disk.
        _flush_results_to_workspace(ctx)
        _inject_empty_output_errors(ctx)
        _inject_static_pattern_errors(ctx)
        # Re-run the runtime simulator so runtime errors (nil-handle access,
        # forward references, bad arg counts, accidental globals) are
        # re-injected.  Static + syntax re-checks alone would otherwise wipe
        # them and falsely report "all violations resolved".
        try:
            ctx.runtime_errors = []
            from runtime_sim import run_runtime_sim as _run_rtsim_rev
            _rtsim_rev_errors = _run_rtsim_rev(ctx)
            if _rtsim_rev_errors:
                ctx.pre_flight_errors += (
                    "\n## ⚡ Runtime Simulation Errors\n"
                    + "\n".join(f"  {e}" for e in _rtsim_rev_errors)
                    + "\n"
                )
        except Exception as _rtsim_rev_ex:
            print(f"  [Pre-Flight] ⚠ RuntimeSim re-validation failed: {_rtsim_rev_ex}")
        # Re-run luac so disk-level syntax errors are reflected in pre_flight_errors.
        import subprocess as _sp_recheck
        for _rc_lf in ctx.project_root.rglob("*.lua"):
            if _rc_lf.stem.startswith("test_task"):
                continue
            try:
                _rc_proc = _sp_recheck.run(
                    ["luac", "-p", str(_rc_lf)], capture_output=True, text=True, timeout=30
                )
                if _rc_proc.returncode != 0:
                    _rc_err = _rc_proc.stderr.strip().replace(str(_rc_lf), _rc_lf.name)
                    # Revert-on-regression: restore the last luac-clean snapshot
                    # (seeded from the clean scaffold by the anchor invariant) so a
                    # broken arch-fix can never persist into the next review cycle.
                    _clean_map = getattr(ctx, '_last_luac_clean_anchor', None) or {}
                    try:
                        _rc_rel = _rc_lf.relative_to(ctx.project_root).as_posix()
                    except ValueError:
                        _rc_rel = _rc_lf.name
                    _clean_snap = _clean_map.get(_rc_rel)
                    if _clean_snap:
                        try:
                            atomic_write_text(_rc_lf, _clean_snap)
                            print(f"  [Arch-Fix Revert] \u26d4 Syntax error \u2014 REVERTED "
                                  f"{_rc_lf.name} to last luac-clean snapshot ({len(_clean_snap)} chars).")
                            continue
                        except Exception as _rc_rv_e:
                            print(f"  [Arch-Fix Revert] \u26a0 revert failed: {_rc_rv_e}")
                    ctx.pre_flight_errors += (
                        f"\n## ✅ Lua Syntax Error (post-fix) -- {_rc_lf.name}\n"
                        f"```\n{_rc_err}\n```\n"
                    )
            except (FileNotFoundError, Exception):
                break

        # ── Holistic File-Level Dedup Pass (Fix 4) ──────────────────────────
        # The per-domain arch fix operates on individual task outputs and can
        # create duplicate function definitions (e.g. every task generates
        # "function OnLoadStatic() end"). This pass reads the actual merged
        # file on disk, detects duplicate function patterns, and requests a
        # SINGLE unified patch from the LLM to deduplicate the file.
        if ctx.pre_flight_errors:
            _dup_re = re.compile(r"duplicate function definition '(\w+)'")
            _dup_files: dict = {}  # file_path -> list of duplicate function names
            for _err_line in ctx.pre_flight_errors.splitlines():
                _dm = _dup_re.search(_err_line)
                if _dm:
                    _df_err = _err_line.strip()
                    # Extract the file name from the error line (heuristic: look for `...`)
                    _ff = _df_err.split("`") if "`" in _df_err else []
                    _fname = _ff[1] if len(_ff) > 1 else ""
                    if _fname:
                        if _fname not in _dup_files:
                            _dup_files[_fname] = []
                        _dup_files[_fname].append(_dm.group(1))

            if _dup_files:
                print(f"  [Holistic Dedup] 🧹 Detected duplicate functions in {len(_dup_files)} file(s): "
                      f"{', '.join(_dup_files.keys())}")
                for _df_name, _dup_funcs in _dup_files.items():
                    _df_path = ctx.project_root / _df_name
                    if not _df_path.is_file():
                        continue
                    try:
                        _df_content = _df_path.read_text(encoding="utf-8", errors="replace")
                    except Exception:
                        continue
                    if not _df_content.strip():
                        continue

                    # Build a focused dedup prompt
                    _dedup_funcs_list = ", ".join(set(_dup_funcs))
                    _dedup_input = (
                        f"## Lua File with Duplicate Functions\n"
                        f"**File:** `{_df_name}`\n"
                        f"**Duplicate functions detected:** {_dedup_funcs_list}\n\n"
                        f"**Current file content:**\n"
                        f"```lua\n{_df_content}\n```\n\n"
                        f"**Fix mandate:**\n"
                        f"1. The functions `{_dedup_funcs_list}` appear MULTIPLE times in this file.\n"
                        f"2. Keep EXACTLY ONE copy of each function with ALL content merged into it.\n"
                        f"3. Do NOT add new code, wrappers, or scaffolding.\n"
                        f"4. Output ONLY the corrected complete file prefixed with `### {_df_name}`.\n"
                        f"5. Do NOT output any SEARCH/REPLACE blocks or prose commentary.\n"
                        f"6. Do NOT emit placeholders or skeleton stubs.\n"
                    )

                    _dedup_system = (
                        "You are a precise code deduplicator. "
                        "You receive a Lua file with duplicate function definitions. "
                        "Remove the duplicates while preserving ALL unique code from each instance. "
                        "Output the complete deduplicated file with no commentary."
                    )

                    _dedup_result = call_ollama(
                        _dedup_system, _dedup_input,
                        f"Holistic Dedup [{_df_name}]",
                        # Use the domain-specific model for Lua
                        getattr(ctx, 'domain_registry', {})\
                            .get("Lua", {})\
                            .get("model", "") or __import__('pipeline').EXECUTION_MODEL
                    )

                    # Extract the deduplicated code block
                    _dedup_code = ""
                    _dedoc_match = re.search(
                        r"###\s*[^\n]*\n(.*)", _dedup_result, re.DOTALL
                    )
                    if _dedoc_match:
                        _dedup_code = _dedoc_match.group(1).strip()
                    else:
                        # Fallback: try code fence
                        _dedoc_fence = re.search(
                            r"```(?:lua)?\n(.*?)```", _dedup_result, re.DOTALL
                        )
                        if _dedoc_fence:
                            _dedup_code = _dedoc_fence.group(1).strip()

                    if _dedup_code and len(_dedup_code) > 20:
                        # Apply the deduplicated content to the file
                        try:
                            from _helpers_io import atomic_write_text as _staging_write
                            _staging_write(_df_path, _dedup_code)
                        except Exception:
                            _df_path.write_text(_dedup_code, encoding="utf-8")
                        print(f"  [Holistic Dedup] ✅ Applied deduplicated content to {_df_name} "
                              f"({len(_dedup_code)} chars)")
                        # Also update the merged key in all_results_dict so the
                        # review loop sees the corrected content
                        _merged_key = f"merged:{_df_name.replace('/', '\\').replace('\\', '/')}"
                        for _mr_key in list(ctx.all_results_dict.keys()):
                            if _mr_key.startswith("merged:") and _df_name in _mr_key:
                                ctx.all_results_dict[_mr_key] = _dedup_code
                                print(f"  [Holistic Dedup] ✅ Updated merged key '{_mr_key}' in results dict")
                                break
                    else:
                        print(f"  [Holistic Dedup] ⚠ Could not extract valid dedup output for {_df_name}")

            # Re-validate after holistic dedup pass
            if ctx.pre_flight_errors:
                ctx.pre_flight_errors = ""
                _flush_results_to_workspace(ctx)
                _inject_empty_output_errors(ctx)
                _inject_static_pattern_errors(ctx)
                try:
                    ctx.runtime_errors = []
                    from runtime_sim import run_runtime_sim as _run_rtsim_rev2
                    _rtsim_rev2_errors = _run_rtsim_rev2(ctx)
                    if _rtsim_rev2_errors:
                        ctx.pre_flight_errors += (
                            "\n## ⚡ Runtime Simulation Errors\n"
                            + "\n".join(f"  {e}" for e in _rtsim_rev2_errors)
                            + "\n"
                        )
                except Exception as _rtsim_rev2_ex:
                    print(f"  [Pre-Flight] ⚠ RuntimeSim re-validation failed: {_rtsim_rev2_ex}")

        if ctx.pre_flight_errors:
            print(f"  [Pre-Flight] ⚠ {ctx.pre_flight_errors.count('## Static') + ctx.pre_flight_errors.count('## Empty') + ctx.pre_flight_errors.count('## Lua Syntax')} "
                  f"violation(s) remain after arch-fix.")
        else:
            print("  [Pre-Flight] ✅ All violations resolved after arch-fix.")

    return ctx
