"""Verify all anchor line numbers in pipeline.py"""
import re

with open('pipeline.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()
print(f'Total lines: {len(lines)}')

anchors = {
    'OLLAMA_HOST': r'^OLLAMA_HOST\s*=',
    'CODER_MODEL': r'^CODER_MODEL\s*=',
    'REVIEWER_MODEL': r'^REVIEWER_MODEL\s*=',
    'FALLBACK_REVIEWER_MODEL': r'^FALLBACK_REVIEWER_MODEL\s*=',
    'LIBRARIAN_MODEL': r'^LIBRARIAN_MODEL\s*=',
    'SYNTAX_GATE_MODEL': r'^SYNTAX_GATE_MODEL\s*=',
    'INTENT_CLASSIFIER_MODEL': r'^INTENT_CLASSIFIER_MODEL\s*=',
    'EXECUTION_MODEL': r'^EXECUTION_MODEL\s*=',
    'REASONING_MODEL': r'^REASONING_MODEL\s*=',
    'DIRECTOR_MODEL': r'^DIRECTOR_MODEL\s*=',
    'PROJECT_ROOT': r'^PROJECT_ROOT\s*=',
    'SCOPE_FILE_LIMIT': r'^SCOPE_FILE_LIMIT\s*=',
    'SCOPE_LINE_LIMIT': r'^SCOPE_LINE_LIMIT\s*=',
    'OLLAMA_TIMEOUT': r'^OLLAMA_TIMEOUT\s*=',
    'OLLAMA_NUM_CTX': r'^OLLAMA_NUM_CTX\s*=',
    'MAX_TOKENS': r'^MAX_TOKENS\s*=',
    'CHECKPOINT_DIR': r'^CHECKPOINT_DIR\s*=',
    'MEMORY_DIR': r'^MEMORY_DIR\s*=',
    'LEDGER_MEMORY_RULE': r'^LEDGER_MEMORY_RULE\s*=\s*\(',
    'TokenBudget': r'^class TokenBudget\b',
    'OffloadStore': r'^class OffloadStore\b',
    'TagSuggester': r'^class TagSuggester\b',
    '_DOC_CACHE_TTL': r'^_DOC_CACHE_TTL\s*=',
    '_DOC_CACHE_MAX': r'^_DOC_CACHE_MAX\s*=',
    '_MAX_OUTPUT_CHARS': r'^_MAX_OUTPUT_CHARS\s*=',
    # Removed during refactoring (no longer in pipeline.py):
    # SESSION_TIMELINE_LOCK, LEDGER_WRITE_LOCK, _LOCK_TIMEOUT, _timed_lock
    'log_to_session_timeline': r'^def log_to_session_timeline\b',
    'ALL_DOMAINS': r'^ALL_DOMAINS\s*=',
    'PERSONA_MAP': r'^PERSONA_MAP\s*=',
    'REASONING_GATE_DOMAINS': r'^REASONING_GATE_DOMAINS\s*=',
    'DIRECTOR_SYSTEM': r'^DIRECTOR_SYSTEM\s*=',
    'REVIEW_SYSTEM': r'^REVIEW_SYSTEM\s*=',
    'REVIEW_PROMPT': r'^REVIEW_PROMPT\s*=',
    'FINAL_APPROVAL_SYSTEM': r'^FINAL_APPROVAL_SYSTEM\s*=',
    'SELF_CORRECT_SYSTEM': r'^SELF_CORRECT_SYSTEM\s*=',
    'ARCHITECT_FIX_SYSTEM': r'^ARCHITECT_FIX_SYSTEM\s*=',
    'LIBRARIAN_SYSTEM': r'^LIBRARIAN_SYSTEM\s*=',
    'DIAGNOSTIC_ORACLE_SYSTEM': r'^DIAGNOSTIC_ORACLE_SYSTEM\s*=',
    'INTENT_ROUTER_SYSTEM': r'^INTENT_ROUTER_SYSTEM\s*=',
    'INTENT_CLASSIFIER_SYSTEM': r'^INTENT_CLASSIFIER_SYSTEM\s*=',
    'SEARCH_MEMORY_SYSTEM': r'^SEARCH_MEMORY_SYSTEM\s*=',
    'MESH_AGENT_SYSTEM_EXTENSION': r'^MESH_AGENT_SYSTEM_EXTENSION\s*=',
    'AGENT_FILE_TOOLS_PROMPT': r'^AGENT_FILE_TOOLS_PROMPT\s*=',
    'classify_intent': r'^def classify_intent\b',
    'search_memory': r'^def search_memory\b',
    'get_project_state': r'^def get_project_state\b',
    'build_director_prompt': r'^def build_director_prompt\b',
    'curate_project_structure': r'^def curate_project_structure\b',
    'extract_gdd_sections': r'^def extract_gdd_sections\b',
    'recursive_librarian': r'^def recursive_librarian\b',
    'parse_file_references': r'^def parse_file_references\b',
    'fetch_referenced_files': r'^def fetch_referenced_files\b',
    'extract_signals': r'^def extract_signals\b',
    'extract_double_check': r'^def extract_double_check\b',
    'get_verdict': r'^def get_verdict\b',
    'handle_fetch_signal': r'^def handle_fetch_signal\b',
    'read_offloaded_file': r'^def read_offloaded_file\b',
    'handle_read_offloaded_signal': r'^def handle_read_offloaded_signal\b',
    '_page_out_context': r'^def _page_out_context\b',
    'ensure_ledger_header': r'^def ensure_ledger_header\b',
    '_generate_module_name': r'^def _generate_module_name\b',
    '_append_to_ledger': r'^def _append_to_ledger\b',
    'save_checkpoint': r'^def save_checkpoint\b',
    'load_checkpoint': r'^def load_checkpoint\b',
    'list_checkpoints': r'^def list_checkpoints\b',
    'resolve_agent_name': r'^def resolve_agent_name\b',
    'get_agent_system': r'^def get_agent_system\b',
    'run_mesh_pipeline': r'^def run_mesh_pipeline\b',
    'run_pipeline': r'^def run_pipeline\b',
    'generate_failure_report': r'^def generate_failure_report\b',
    'submit_mesh_task': r'^def submit_mesh_task\b',
    'get_mesh_task_status': r'^def get_mesh_task_status\b',
    'list_mesh_tasks': r'^def list_mesh_tasks\b',
    'cancel_mesh_task': r'^def cancel_mesh_task\b',
    'get_mesh_work_queue': r'^def get_mesh_work_queue\b',
    'get_mesh_results': r'^def get_mesh_results\b',
    'detect_cross_agent_edits': r'^def detect_cross_agent_edits\b',
    'resolve_conflict': r'^def resolve_conflict\b',
    'register_progress_listener': r'^def register_progress_listener\b',
    'format_file_context': r'^def format_file_context\b',
    'find_relevant_files': r'^def find_relevant_files\b',
    'get_available_domains_text': r'^def get_available_domains_text\b',
    'get_unavailable_domains_text': r'^def get_unavailable_domains_text\b',
    'SignalType': r'^class SignalType\b',
    'MeshSignal': r'^class MeshSignal\b',
    'ConsensusResult': r'^class ConsensusResult\b',
    'Task': r'^class Task\b',
    'parse_signal': r'^def parse_signal\b',
    'build_anchor_toc': r'^def build_anchor_toc\b',
    'ledger_toc': r'^def ledger_toc\b',
    'get_offload_store': r'^def get_offload_store\b',
    # Removed during refactoring: _offload_single_block, _build_offload_placeholder
    'SESSION_TIMELINE_PATH': r'^SESSION_TIMELINE_PATH\s*=',
    'get_referenced_files_cache': r'^def get_referenced_files_cache\b',
    'set_referenced_files_cache': r'^def set_referenced_files_cache\b',
    'handle_file_read': r'^def handle_file_read\b',
    'handle_file_list': r'^def handle_file_list\b',
    'SIGNAL_PATTERNS': r'^SIGNAL_PATTERNS\s*=',
    'GDD_SECTION_MAP': r'^GDD_SECTION_MAP\s*=',
    'KEYWORD_TO_SECTION': r'^KEYWORD_TO_SECTION\s*=',
}

for name, pattern in sorted(anchors.items(), key=lambda x: x[0]):
    found = False
    for i, line in enumerate(lines):
        if re.match(pattern, line):
            print(f'L{i+1}: {name}')
            found = True
            break
    if not found:
        print(f'NOT FOUND: {name} (pattern: {pattern})')
