#!/usr/bin/env python3
"""
serve_xgrammar.py — Constrained deployment inference (vLLM / SGLang + xgrammar).
====================================================================================

ARCHITECTURAL STANDARD #4 (Constrained Inference):
    Deployment configurations MUST use the ``xgrammar`` backend for guided
    decoding.  xgrammar compiles the JSON schema generated by our Pydantic
    contracts (``structured_schemas.py``) into a token-level grammar automaton,
    which mathematically guarantees the model can only emit structurally valid
    output — no malformed JSON can leave the sampler.

    This module provides:
      1. ``build_xgrammar_schema()`` — JSON schema for any registered Pydantic model.
      2. ``VLLMXGrammarServer`` — vLLM ``LLM`` + ``GuidedDecodingParams(backend="xgrammar")``.
      3. ``SGLangXGrammarServer`` — SGLang ``RuntimeEndpoint`` with xgrammar JSON mode.
      4. ``serve()`` — a FastAPI HTTP facade that mirrors Ollama's ``/api/chat``
         surface so the existing pipeline can call it without a code change.

16 GB VRAM note:
    vLLM/SGLang are heavier than Ollama's mmap runner.  For the Steam Deck the
    recommended deployment remains Ollama + ``structured_client.py``; the servers
    below are for a dedicated 16 GB dGPU.  All three paths share the SAME Pydantic
    schema so a result is validated identically regardless of the backend.

Dependencies:
    pip install xgrammar vllm        # vLLM path
    pip install xgrammar sglang      # SGLang path
    pip install fastapi uvicorn      # optional HTTP facade
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Any, Optional

# The contract source of truth — same schemas the pipeline extracts with.
from structured_schemas import SCHEMA_REGISTRY, get_schema


def build_xgrammar_schema(schema_name: str) -> dict[str, Any]:
    """Emit the JSON schema that xgrammar will compile into a grammar automaton.

    xgrammar accepts a raw JSON schema dict (``{"type": "object", ...}``).  Pydantic
    v2's ``model_json_schema()`` produces exactly that shape; we only need to make
    sure ``additionalProperties`` / ``required`` are resolved for strictness.
    """
    model = get_schema(schema_name)
    schema = model.model_json_schema()
    # xgrammar expects a "type" root; Pydantic already provides it.  Ensure strict
    # rejection of unknown keys so the LLM cannot smuggle in undeclared fields.
    schema.setdefault("additionalProperties", False)
    return schema


# ---------------------------------------------------------------------------
#  vLLM
# ---------------------------------------------------------------------------

@dataclass
class VLLMConfig:
    model: str = os.environ.get("XGRAMMAR_MODEL", "Qwen/Qwen2.5-Coder-7B-Instruct")
    tensor_parallel_size: int = int(os.environ.get("VLLM_TP", "1"))
    max_model_len: int = int(os.environ.get("VLLM_MAX_MODEL_LEN", "32768"))
    gpu_memory_utilization: float = float(os.environ.get("VLLM_GPU_MEM", "0.90"))
    enforce_eager: bool = True  # avoids CUDA graph capture VRAM spike on 16 GB
    dtype: str = "half"
    schema_name: str = "task_decomposition"


class VLLMXGrammarServer:
    """vLLM serving with token-level xgrammar syntactic compliance."""

    def __init__(self, config: Optional[VLLMConfig] = None) -> None:
        self.config = config or VLLMConfig()
        from vllm import LLM, SamplingParams
        from vllm.sampling_params import GuidedDecodingParams

        self._LLM = LLM
        self._SamplingParams = SamplingParams
        self._GuidedDecodingParams = GuidedDecodingParams

        self.llm = self._LLM(
            model=self.config.model,
            tensor_parallel_size=self.config.tensor_parallel_size,
            max_model_len=self.config.max_model_len,
            gpu_memory_utilization=self.config.gpu_memory_utilization,
            enforce_eager=self.config.enforce_eager,
            dtype=self.config.dtype,
            # Backend-wide default; per-request override also shown in generate().
            guided_decoding_backend="xgrammar",
        )

    def generate(self, prompt: str, schema_name: Optional[str] = None) -> dict[str, Any]:
        """Generate a single constrained completion.

        ``GuidedDecodingParams(json=..., backend="xgrammar")`` compiles the schema
        into a context-free grammar on the fly and constrains every sampled token.
        """
        name = schema_name or self.config.schema_name
        json_schema = build_xgrammar_schema(name)

        guided = self._GuidedDecodingParams(json=json_schema, backend="xgrammar")
        params = self._SamplingParams(
            temperature=0.0,
            max_tokens=4096,
            guided_decoding=guided,
        )
        outputs = self.llm.generate([prompt], sampling_params=params)
        raw = outputs[0].outputs[0].text

        # Belt-and-braces: re-validate against Pydantic so a parsed object is
        # returned even though xgrammar already guarantees syntactic validity.
        return {"raw": raw, "model": get_schema(name).model_validate_json(raw).model_dump()}


# ---------------------------------------------------------------------------
#  SGLang
# ---------------------------------------------------------------------------

class SGLangXGrammarServer:
    """SGLang serving using xgrammar's JSON-schema grammar backend."""

    def __init__(self, model: str = "Qwen/Qwen2.5-Coder-7B-Instruct") -> None:
        self.model = model

    def generate(self, prompt: str, schema_name: str = "task_decomposition") -> dict[str, Any]:
        import sglang as sgl
        from sglang.srt.constrained.xgrammar_backend import XGrammarBackend  # noqa: F401

        json_schema = build_xgrammar_schema(schema_name)

        @sgl.function
        def constrained(s):
            s += prompt
            # xgrammar compiles the schema into a grammar; every token must conform.
            s += sgl.gen("answer", max_tokens=4096, json_schema=json_schema)

        state = constrained.run()
        raw = state["answer"]
        return {"raw": raw, "model": get_schema(schema_name).model_validate_json(raw).model_dump()}


# ---------------------------------------------------------------------------
#  Optional HTTP facade (Ollama-compatible /api/chat surface)
# ---------------------------------------------------------------------------

def serve(model: str = "Qwen/Qwen2.5-Coder-7B-Instruct", port: int = 11435) -> None:
    """Run a minimal FastAPI server whose response is always schema-valid.

    Endpoint:
        POST /v1/chat/completions   {"model", "messages", "schema"}
        POST /v1/generate           {"prompt", "schema"}
    """
    try:
        from fastapi import FastAPI
        from pydantic import BaseModel as _PydBase
        import uvicorn
    except ImportError as exc:
        raise ImportError("serve() requires `fastapi` and `uvicorn`") from exc

    app = FastAPI(title="xgrammar constrained inference")
    vllm = VLLMXGrammarServer(VLLMConfig(model=model))

    class ChatRequest(_PydBase):
        model: str = model
        messages: list[dict[str, Any]]
        schema: str = "task_decomposition"

    class GenerateRequest(_PydBase):
        prompt: str
        schema: str = "task_decomposition"

    @app.post("/v1/chat/completions")
    def chat(req: ChatRequest) -> dict[str, Any]:
        prompt = "\n".join(f"{m.get('role', 'user')}: {m.get('content', '')}" for m in req.messages)
        result = vllm.generate(prompt, req.schema)
        return {"model": req.model, "choices": [{"message": {"content": result["raw"]}}]}

    @app.post("/v1/generate")
    def generate(req: GenerateRequest) -> dict[str, Any]:
        return vllm.generate(req.prompt, req.schema)

    uvicorn.run(app, host="0.0.0.0", port=port)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="xgrammar constrained inference server")
    parser.add_argument("--backend", choices=["vllm", "sglang", "serve"], default="serve")
    parser.add_argument("--model", default="Qwen/Qwen2.5-Coder-7B-Instruct")
    parser.add_argument("--schema", default="task_decomposition",
                        help="Schema registry key: " + ", ".join(sorted(SCHEMA_REGISTRY)))
    parser.add_argument("--prompt", default="Decompose: add a plinko jackpot lane")
    parser.add_argument("--port", type=int, default=11435)
    args = parser.parse_args()

    if args.backend == "serve":
        serve(model=args.model, port=args.port)
    elif args.backend == "vllm":
        srv = VLLMXGrammarServer(VLLMConfig(model=args.model, schema_name=args.schema))
        print(json.dumps(srv.generate(args.prompt), indent=2))
    else:
        srv = SGLangXGrammarServer(model=args.model)
        print(json.dumps(srv.generate(args.prompt, args.schema), indent=2))
